name: CI Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependências
        run: npm install
      - name: Build do projeto
        run: npm run build